version: "3.9"

services:
    seller:
        image: "sale"
        depends_on:
            -   postgre
        networks:
            - postgre
        ports:
            - "8080:8080"
        volumes:
            - /home/jkrus/.config/sale-announcements:/root/.config/sale-announcements
        command: ./sale-announcements start

    postgre:
        image: "postgres:14.2"
        environment:
            POSTGRES_DB: "saledb"
            POSTGRES_USER: "sale"
            POSTGRES_PASSWORD: "sale"
        networks:
            - postgre
        ports:
            - "5432:5432"
networks:
    postgre:
        driver: bridge